# Site settings
baseurl = "https://santiago2020.satrdays.org" # Change this to the base url after netlify deploy, e.g. "https://cardiff2019.satrdays.org/"
languageCode = "en-us"
title = "satRday"
theme = ["hugo-satrdays-theme", "hugo-agency-theme"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable taxonomies that are not used https://discourse.gohugo.io/t/found-no-layout-for-taxonomyterm-language-en-output-format-html/16376
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "satRday Santiago"
  description = "Conferencia de R en Santiago de Chile"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = ["css/satrday.css"]
  custom_js  = []
  favicon    = "img/favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Página no encontrada"
    text = "Por favor, visita santiago2020.satrdays.org"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "satRday"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    services = "Acerca de"
    portfolio = "Charlas"
    eventbrite = "Registro"
    about = "Calendario"
    team = "Equipo"
    contact = "Contáctanos"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://satrdays.org/"
      name = "satRdays.org"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "satRday Santiago"
    subtitle = "Una conferencia de y para la comunidad de R en Santiago de Chile"
    bg = true
    buttonText = "Más"


  # About [Services] section
  [params.services]
    enable = true
    title = "Acerca de"
    #subtitle = "Detalles de esta segunda ediciónde satRday Santiago"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "Cuándo"
      description = "18 de abril en EYU"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Conoce"
      description = "Aprende sobre los últimos desarrollos de R"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Útil"
      description = "Conoce aplicaciones prácticas de R"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Comunidad"
      description = "Un evento organizado por y para la comunidad"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-money"
      title = "Asequible"
      description = "Evento gratuito"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-universal-access"
      title = "Accesible"
      description = "Un ambiente inclusivo y respetuoso"
      url = "#"

  # Register section
  # You only need ONE of these active
  #[params.tito]
  #  enable = true
  #  title = "Register"
  #  bg = true
  #  accountevent = "ultimateconf/2013"
      # Go to https://ti.to/ and find the account (under your user) and event pair string e.g. "cardiff-satrday/2018"
      # include botht the account and event in a string, seperated by /, with no spaces

  #[params.eventbrite]
  #  enable = true
  #  title = "Register"
  #  bg = true
  #  eid = "32416000129"
      # Go to https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_GB
      # Follow instructions to discover your 'Website Integration' embeddable iframe
      # Take ONLY the numeric string between "eid=" and "&ref=etckt"
      # Supply this string as the value to `eid` above

  #[params.tickettailor]
  #  enable = true
  #  title = "Register"
  #  bg = true
  #  eventviewid = "162430"
      # Go to www.tickettailor.com and open your event page
      # Note the number at the end of the url e.g. https://www.tickettailor.com/event/view/id/162430
      # Supply the number ONLY in `eventviewid`

  #Call for papers section
  [params.callforpapers]
    enable = true
    title = "Presentación de propuestas"
    bg = false
  #  CfSpage = "/test3490"
      # Go to Organizer > My Events > Dashboard and copy the "CfS Page" string into the `CfSpage` value
  #  dates = "09 Aug - 21 Sep 2018"

  # Hackathon section
  [params.hackathon]
    enable = true
    bg = false
    title = "Evento pre-conferencia: viernes 17 de abril"
    subtitle="Participa en una tarde de desarrollo de paquetes, proyectos y visualización de datos."
    brief1="Pronto más detalles. ¡Inscripción a partir del 1 de abril!"
  #  brief2="But you __MUST__ hardcode html links <a href= 'www.google.com' > google  </a> for further info."
  #  location= "The place we're going it"
  #  dates = "17 November 2019"
  #  times= "13:00-17:30"
  #  website_name="google"
  #  website_url="www.google.com"

  # Talk [Portfolio] section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Charlas"
    subtitle = "Por anunciar"
    bg = true

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  # Schedule section
  [params.schedule]
    enable = true
    title = "Programa"
    bg = false

  # Important Dates [About] section
  [params.about]
    enable = true
    title = "Fechas importantes"
    subtitle = "¡Atención!"
    endpoint = "satRday Santiago 18/04/2020"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "anuncio.png"
      date = "Febrero 2020"
      title = "Anuncio inicial"
      description = "¡Se viene la segunda edición de satRday Santiago!"

    [[params.about.events]]
      img = "tickets.png"
      date = ""
      title = "Registro para el evento del sábado"
      description = "No te quedes si tu cupo"

    [[params.about.events]]
      img = "microfono.png"
      date = ""
      title = "Llamado a presentación de trabajos"
      description = "¡Envía tu propuesta!"

    [[params.about.events]]
      img = "deadline.png"
      date = "15 de marzo 2020"
      title = "Fin envío de propuestas"
      description = "Cierre del llamado a presentación de trabajos"

      [[params.about.events]]
        img = "equipo.png"
        date = "1 abril 2020"
        title = "Registro para el evento del viernes"
        description = "Trabaja en conjunto con la comunidad"

  # Location section
  [params.location]
    enable = true
    title = "Ubicación"
    bg = true
    iframesrc = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3330.7546712515677!2d-70.57278611988689!3d-33.40356408088149!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662ced906907077%3A0xd8f748dc2aed271!2sCerro%20El%20Plomo%206000%2C%20Las%20Condes%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses-419!2scl!4v1581615134674!5m2!1ses-419!2scl"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Equipo"
    subtitle = "Las personas detrás del evento"
    bg = false
    description = ""
    speakers = "Speakers"



    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "riva-quiroga.jpeg"
      name = "Riva Quiroga"
      position = "R-Ladies Santiago/Valparaíso"
      #reportsTo = ""
      #livesIn = "[Munich, Germany](#some-maps-url)"
      #scope = [
      #  "Role 1 for [thing 1](#)",
      #  "Role 2 for [thing 2](#)",
      #  "Role 3 for [thing 3](#)"
      #]
      # For bio markdown and even multiline strings are available.
      #bio = """I do things,
      #and stuff"""
      social = [
      ["fa-twitter", "https://twitter.com/rivaquiroga"],
      ["fa-github", "https://github.com/rivaquiroga"],
      ["fa-laptop", "http://rivaquiroga.cl"]
      ]

    [[params.team.members]]
      img = "gaby-sandoval.jpeg"
      name = "Gabriela Sandoval"
      position = "R-Ladies Santiago"
      social = [
      ["fa-twitter", "https://twitter.com/GabySandovalM"],
      ["fa-github", "https://github.com/GabySandovalM"]
      ]

    [[params.team.members]]
      img = "patricio-cofre.jpeg"
      name = "Patricio Cofré"
      position = "Grupo de Usuarios de R - Santiago"
      social = [
      ["fa-twitter", "https://twitter.com/pcofre"],
      ["fa-laptop", "http://metricarts.com"],
      ["fa-linkedin", "http://www.linkedin.com/in/pcofre"]
      ]

      [[params.team.members]]
        img = "joshua-kunst.jpeg"
        name = "Joshua Kunst"
        position = "Grupo de Usuarios de R - Santiago"
        social = [
        ["fa-twitter", "https://twitter.com/jbkunst"],
        ["fa-github", "https://github.com/jbkunst"],
        ["fa-laptop", "http://jkunst.com/"],
        ["fa-linkedin", "https://www.linkedin.com/in/joshuakunst/"]
        ]
  # Client section
  [params.clients_list]
    enable = true
    # Possibility to center items
    #center = true
    # Optional client title specifying the involvement
    title = "Sponsors"
    bg = true

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    # Suggestion: .svg in the size of 280px*80px looks good
    [[params.clients]]
      logo = "ey_metricarts.png"
      link = "https://metricarts.com/"

    [[params.clients]]
      logo = "microsoft.png"
      link = "https://www.microsoft.com/es-cl/"

    [[params.clients]]
      logo = "stickermule.png"
      link = "http://www.stickermule.com/supports/satrdaysantiago"

    [[params.clients]]
      logo = ""
      link = "#"

  [params.diversity]
    enable = true
    title = "Código de conducta"
    bg = true

  # Contact section
  [params.contact]
    enable = true
    title = "Contacto"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "satrdaysantiago@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "https://twitter.com/satrdaysantiago"
      title = "Twitter"

    [[params.footer.social]]
      icon = "fa-github"
      link = "https://github.com/satRdays"
      title = "GitHub"

    [[params.footer.quicklinks]]
      text = "Imagen portada: Javmoraga"
      link = "https://es.m.wikipedia.org/wiki/Archivo:Santiago_de_Chile_de_noche.jpg"

    [[params.footer.quicklinks]]
      text = "Licencia imagen: CC BY-SA 3.0"
      link = "https://creativecommons.org/licenses/by-sa/3.0/deed.es"
